### ISSUE TITLE
How to compute the text embedding and edit direction?

### ISSUE THREAD

**Issue by fortunechen** [pix2pixzero/pix2pix-zero#1]
Hi, authors!

Congrats for your good work. I wonder how the text embedding and edit direction are computed? 

If the dimension of text embedding is 1x768, the cross attention map will be full of 1, which causes cross attention map meaningless

If the dimension of text embedding is N（N=77 in CLIP）x768,  then edit direction will be Nx768. However, the edit direction should be a vector.

Looking forward for your answer.

Best regards.

**Comment by pix2pixzero** [comment]
Hi, 

Thank you for your interest in our work! 
The direction vectors are indeed 77x768, we have just uploaded the instructions and the script for computing custom direction vectors.
Let us know if you still have some questions/issues computing new directions! 

Regards,
Authors

**Comment by fortunechen** [comment]
Thx for  your explanation and open-sourcing your project
