### ISSUE TITLE
TypeError: deprecate() got an unexpected keyword argument 'message'

### ISSUE THREAD

**Issue by nancy6o6** [pix2pixzero/pix2pix-zero#24]
Thanks for your sharing!
I got this error "TypeError: deprecate() got an unexpected keyword argument 'message'" in "diffusers/models/cross_attention.py:260 in prepare_attention_mask" when running inversion.py. 
I think it may be a version issue. I wonder which version of diffusers is used in your experiment.
If it's not due to the version, do you know anything about this error?

**Comment by nancy6o6** [comment]
I fix the above problem by slightly modifying the definition of deprecate() in diffusers/utils/d │
│ eprecation_utils.py. However, I got a new ValueError reported by deprecate():
ValueError: The deprecation tuple ('batch_size=None', '0.0.15', 'Not passing the 
`batch_size` parameter to `prepare_attention_mask` can lead to incorrect attention 
mask preparation and is deprecated behavior. Please make sure to pass `batch_size` to
`prepare_attention_mask` when preparing the attention_mask.') should be removed since
diffusers' version 0.14.0 is >= 0.0.15
I think it's still a version issue.

**Comment by ty625911724** [comment]
Have you solved this problem? If yes, could your please give some suggestions? Thanks!

**Comment by ty625911724** [comment]
It seems that the diffusers should be 0.12.0 version.
