### ISSUE TITLE
Cannot make Conda environment

### ISSUE THREAD

**Issue by albusdemens** [pix2pixzero/pix2pix-zero#8]
Hello, thank you for sharing your work! I tried creating the Conda environment running `conda env create -f environment.yml`, but the process got stuck with the message `Solving environment: /`. I have the same issue both on WSL and on Ubuntu. Am I skipping any pre-installation step? Thanks

**Comment by albusdemens** [comment]
Problem solved - I installed using python 3.7.2.

**Comment by fikry102** [comment]
> Problem solved - I installed using python 3.7.2.

What does it mean? use `conda env create -f environment.yml`?

**Comment by miriam-horovicz-ni** [comment]
@repoholder23 @fikry102  Can you specify how you solved it? I face same issue. Thanks!
